services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nautsladder_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    mem_limit: 256m
volumes:
  db:
    driver: local
